server:
  servlet:
    context-path: /exchange/api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exchangeDatabase?useSSL=false&serverTimezone=UTC
    username: mysqlexchange123
    password: mysqlexchange123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update